---

- name: Extract kubeadm join command
  delegate_to: localhost
  become: false
  shell: grep -A 1 "kubeadm join" {{ playbook_dir }}/roles/k8s-worker/tasks/kubeadm_init_output_join_command.txt
  register: join_cmd_output

- debug:
    var: join_cmd_output.stdout

- name: Run kubeadm join on worker nodes
  ansible.builtin.shell: "{{ join_cmd_output.stdout }}"