---
- name: Forwarding IPv4 and letting iptables see bridged traffic
  copy:
    dest: /etc/modules-load.d/k8s-conf
    content:  |
      overlay
      br_netfilter
    owner: "{{ owner }}"
    group: "{{ group_owner }}"
    mode: '0644'

- name: Load the kernel modules overlay and br_netfilter
  command: modprobe {{ item }}
  loop:
    - overlay
    - br_netfilter

- name: Create sysctl config file for kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    owner: "{{ owner }}"
    group: "{{ group_owner }}"
    mode: '0644'

- name: Apply sysctl settings
  command: sysctl --system

- name: Verify that the br_netfilter, overlay modules are loaded
  shell: |
    lsmod | grep br_netfilter || echo "br_netfilter NOT loaded"
    lsmod | grep overlay || echo "overlay NOT loaded"
  register: mod_check

- name: Display kernel modules status
  debug:
    msg: "{{ mod_check.stdout_lines }}"

- name: verify that system variables are set to 1 in your sysctl config
  command: sysctl {{ item }}
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward
