---
- name: Create .kube directory in users home
  ansible.builtin.file:
    path: "{{user_directory}}/.kube"
    state: directory
    mode: '0755'

- name: copy admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{kubeconfig_path}}"
    remote_src: yes

- name: Ensure ownership of the kubeconfig file
  ansible.builtin.file:
    path: "{{kubeconfig_path}}"
    owner: "{{ owner }}"
    group: "{{ group_owner }}"
    
