plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

iam_role_arn: arn:aws:iam::375332747108:role/devops-007-infra-jenkins-slave-dev-role

filters:
  instance-state-name: running

groups:
  master: "'k8s-master' in tags.Name"
  worker: "'k8s-worker' in tags.Name"

compose:
  ansible_host: public_ip_address
  ansible_user: ubuntu
  # ansible_ssh_private_key_file: /Users/csss5tp4/Downloads/k8s-admin.pem